/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/Entity.e.vm.java
 */
package ru.ssau.lexus.domain.entity;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Entity
@Table(schema = "md", name = "token")
public class Token implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Token.class);

    // Raw attributes
    private String id;
    // -- [id] ------------------------

    @NotEmpty
    @Size(max = 2147483647)
    @Column(name = "\"value\"", length = 2147483647)
    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Token id(String id) {
        setId(id);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Token withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Token && hashCode() == other.hashCode());
    }

    ;

    @Override
    public int hashCode() {
        return Objects.hash(this);
    }

    /**
     * Construct a readable string representation for this Token instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Token{" //
                + "id" + getId() //
                + "}";
    }
}