/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/Entity.e.vm.java
 */
package ru.ssau.lexus.domain.entity;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Objects;

import static javax.persistence.GenerationType.IDENTITY;

@Entity
@Table(schema = "list", name = "training_status")
public class TrainingStatus implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(TrainingStatus.class);

    // Raw attributes
    private Long id;
    private String name;
    private String code;
    // -- [id] ------------------------

    @Column(name = "id", precision = 19)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TrainingStatus id(Long id) {
        setId(id);
        return this;
    }

    // -- [name] ------------------------

    @NotEmpty
    @Size(max = 2147483647)
    @Column(name = "name", nullable = false, length = 2147483647)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TrainingStatus name(String name) {
        setName(name);
        return this;
    }
    // -- [code] ------------------------

    @NotEmpty
    @Size(max = 2147483647)
    @Column(name = "code", nullable = false, length = 2147483647)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public TrainingStatus code(String code) {
        setCode(code);
        return this;
    }

    /**
     * Apply the default values.
     */
    public TrainingStatus withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof TrainingStatus && hashCode() == other.hashCode());
    }

    ;

    @Override
    public int hashCode() {
        return Objects.hash(this);
    }

    /**
     * Construct a readable string representation for this TrainingStatus instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return "TrainingStatus{" //
                + "id" + getId() //
                + "name" + getName() //
                + "code" + getCode() //
                + "}";
    }
}