/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/mapper/Mapper.e.vm.java
 */
package ru.ssau.lexus.domain.mapper;

import ru.ssau.lexus.domain.dto.SubscriptionTypeDto;
import ru.ssau.lexus.domain.entity.SubscriptionType;

import org.mapstruct.Mapper;
import java.util.Collection;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper(componentModel = "spring")
public interface SubscriptionTypeMapper {

    @Mappings({})
    SubscriptionTypeDto entityToDto(SubscriptionType entity);

    @Mappings({})
    SubscriptionType dtoToEntity(SubscriptionTypeDto dto);

    Collection<SubscriptionTypeDto> entityToDto(Collection<SubscriptionTypeDto> entity);

    Collection<SubscriptionType> dtoToEntity(Collection<SubscriptionTypeDto> dto);
}