/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/mapper/Mapper.e.vm.java
 */
package ru.ssau.lexus.domain.mapper;

import org.mapstruct.Mapper;

import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import ru.ssau.lexus.domain.dto.TrainingDto;
import ru.ssau.lexus.domain.entity.Training;
import java.util.Collection;

@Mapper(componentModel = "spring")
public interface TrainingMapper {

    @Mappings({
            @Mapping(source ="idClient.id", target = "idClient"),
            @Mapping(source ="idTrainer.id", target = "idTrainer"),
            @Mapping(source ="idType.id", target = "idType"),
            @Mapping(source ="idStatus.id", target = "idStatus")
    })
    TrainingDto entityToDto(Training entity);

    @Mappings({
            @Mapping(target ="idClient.id", source = "idClient"),
            @Mapping(target ="idTrainer.id", source = "idTrainer"),
            @Mapping(target ="idType.id", source = "idType"),
            @Mapping(target ="idStatus.id", source = "idStatus")
    })
    Training dtoToEntity(TrainingDto dto);

    Collection<TrainingDto> entityToDto(Collection<TrainingDto> entity);

    Collection<Training> dtoToEntity(Collection<TrainingDto> dto);
}