/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/mapper/Mapper.e.vm.java
 */
package ru.ssau.lexus.domain.mapper;

import org.mapstruct.Mapper;

import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import ru.ssau.lexus.domain.dto.UserDto;
import ru.ssau.lexus.domain.entity.User;
import java.util.Collection;

@Mapper(componentModel = "spring")
public interface UserMapper {

    @Mappings({
            @Mapping(source ="idGroup.id", target = "idGroup")
    })
    UserDto entityToDto(User entity);

    @Mappings({
            @Mapping(target ="idGroup.id", source = "idGroup")
    })
    User dtoToEntity(UserDto dto);

    Collection<UserDto> entityToDto(Collection<UserDto> entity);

    Collection<User> dtoToEntity(Collection<UserDto> dto);
}