version: '3'
services:
  lexus_postgresql:
    env_file: .env
    image: postgres:9.4
    restart: always
    networks:
      - spring-boot-postgresql-network
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  lexus-service:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
        - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
        - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - spring-boot-postgresql-network
    depends_on:
      - lexus_postgresql
    environment:
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
networks:
  spring-boot-postgresql-network:
    driver: bridge