/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/service/Service.e.vm.java
 */
package ru.ssau.lexus.service;

import java.util.Optional;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ru.ssau.lexus.domain.dto.SubscriptionTypeDto;
import ru.ssau.lexus.domain.entity.SubscriptionType;
import ru.ssau.lexus.domain.mapper.SubscriptionTypeMapper;
import ru.ssau.lexus.repository.crud.SubscriptionTypeRepository;

import lombok.AllArgsConstructor;
import java.util.Collection;
import java.util.stream.Collectors;

@Service
@Transactional
@AllArgsConstructor
public class SubscriptionTypeService {

    protected final SubscriptionTypeRepository repository;

    protected final SubscriptionTypeMapper mapper;

    /**
     * Save a SubscriptionType.
     *
     * @param dto the entity to save.
     * @return the persisted entity.
     */
    public SubscriptionTypeDto save(SubscriptionTypeDto dto) {
        SubscriptionType entity = mapper.dtoToEntity(dto);
        entity = repository.save(entity);
        return mapper.entityToDto(entity);
    }

    /**
     * Get all the SubscriptionTypes.
     *
     * @return the list of entities.
     */
    @Transactional(readOnly = true)
    public Collection<SubscriptionTypeDto> findAll() {
        return repository.findAll().stream().map(mapper::entityToDto).collect(Collectors.toList());
    }

    /**
     * Get one SubscriptionType by id.
     *
     * @param id the id of the entity.
     * @return the entity.
     */
    @Transactional(readOnly = true)
    public Optional<SubscriptionTypeDto> findOne(Long id) {
        return repository.findById(id).map(mapper::entityToDto);
    }

    /**
     * Delete the anodeHist by id.
     *
     * @param id the id of the entity.
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }
}