/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/service/Service.e.vm.java
 */
package ru.ssau.lexus.service;

import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.ssau.lexus.domain.dto.TrainingStatusDto;
import ru.ssau.lexus.domain.entity.TrainingStatus;
import ru.ssau.lexus.domain.mapper.TrainingStatusMapper;
import ru.ssau.lexus.repository.crud.TrainingStatusRepository;

import java.util.Collection;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@Transactional
@AllArgsConstructor
public class TrainingStatusService {

    protected final TrainingStatusRepository repository;

    protected final TrainingStatusMapper mapper;

    /**
     * Save a TrainingStatus.
     *
     * @param dto the entity to save.
     * @return the persisted entity.
     */
    public TrainingStatusDto save(TrainingStatusDto dto) {
        TrainingStatus entity = mapper.dtoToEntity(dto);
        entity = repository.save(entity);
        return mapper.entityToDto(entity);
    }

    /**
     * Get all the TrainingStatuss.
     *
     * @return the list of entities.
     */
    @Transactional(readOnly = true)
    public Collection<TrainingStatusDto> findAll() {
        return repository.findAll().stream().map(mapper::entityToDto).collect(Collectors.toList());
    }

    /**
     * Get one TrainingStatus by id.
     *
     * @param id the id of the entity.
     * @return the entity.
     */
    @Transactional(readOnly = true)
    public Optional<TrainingStatusDto> findOne(Long id) {
        return repository.findById(id).map(mapper::entityToDto);
    }

    /**
     * Delete the anodeHist by id.
     *
     * @param id the id of the entity.
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }
}