/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/EntityMeta_.e.vm.java
 */
package ru.ssau.lexus.domain.metamodel;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import ru.ssau.lexus.domain.entity.SubscriptionType;

@StaticMetamodel(SubscriptionType.class)
public abstract class SubscriptionType_ {

    // Raw attributes
    public static volatile SingularAttribute<SubscriptionType, Long> id;
    public static volatile SingularAttribute<SubscriptionType, String> name;
    public static volatile SingularAttribute<SubscriptionType, String> code;
}