/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/EntityMeta_.e.vm.java
 */
package ru.ssau.lexus.domain.metamodel;

import ru.ssau.lexus.domain.entity.Token;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Token.class)
public abstract class Token_ {

    // Raw attributes
    public static volatile SingularAttribute<Token, String> id;
}