/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/EntityMeta_.e.vm.java
 */
package ru.ssau.lexus.domain.metamodel;

import java.time.LocalDate;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import ru.ssau.lexus.domain.entity.Training;
import ru.ssau.lexus.domain.entity.TrainingStatus;
import ru.ssau.lexus.domain.entity.TrainingType;
import ru.ssau.lexus.domain.entity.User;

@StaticMetamodel(Training.class)
public abstract class Training_ {

    // Raw attributes
    public static volatile SingularAttribute<Training, Long> id;
    public static volatile SingularAttribute<Training, LocalDate> dateTraining;
    public static volatile SingularAttribute<Training, Long> price;

    // Many to one
    public static volatile SingularAttribute<Training, User> idClient;
    public static volatile SingularAttribute<Training, User> idTrainer;
    public static volatile SingularAttribute<Training, TrainingType> idType;
    public static volatile SingularAttribute<Training, TrainingStatus> idStatus;
}