/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/entity/EntityMeta_.e.vm.java
 */
package ru.ssau.lexus.domain.metamodel;

import ru.ssau.lexus.domain.entity.TrainingStatus;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TrainingStatus.class)
public abstract class TrainingStatus_ {

    // Raw attributes
    public static volatile SingularAttribute<TrainingStatus, Long> id;
    public static volatile SingularAttribute<TrainingStatus, String> name;
    public static volatile SingularAttribute<TrainingStatus, String> code;
}