/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/dto/Dto.e.vm.java
 */
package ru.ssau.lexus.domain.dto;

import lombok.Data;

import java.io.Serializable;

@Data
public class RoleDto implements Serializable {

    private Long id;
    private String name;
    private String code;
    private Long idUser;

}
