/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/dto/Dto.e.vm.java
 */
package ru.ssau.lexus.domain.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class SubscriptionTypeDto implements Serializable {

    // Raw attributes

    private Long id;

    private String name;

    private String code;

}
