/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-custom:src/main/java/dto/Dto.e.vm.java
 */
package ru.ssau.lexus.domain.dto;

import java.io.Serializable;
import java.time.LocalDate;

import lombok.Data;

@Data
public class TrainingDto implements Serializable {

    private Long id;
    private LocalDate dateTraining;
    private Long price;

    private Long idClient;
    private Long idTrainer;
    private Long idType;
    private Long idStatus;

}
